<?xml version="1.0" encoding="utf-8"?><Database Name="SpaceAppChallenge" Class="DataAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\sql2008;Initial Catalog=SpaceAppChallenge;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="SpaceAppChallengeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_CARACTERISTICAS" Member="TB_CARACTERISTICAs">
    <Type Name="TB_CARACTERISTICA">
      <Column Name="IdCaracteristicas" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TB_CARACTERISTICA_TB_PERSONAJE_CARACTERISTICA" Member="TB_PERSONAJE_CARACTERISTICAs" ThisKey="IdCaracteristicas" OtherKey="IdCaracteristica" Type="TB_PERSONAJE_CARACTERISTICA" />
    </Type>
  </Table>
  <Table Name="dbo.TB_CONTACTO" Member="TB_CONTACTOs">
    <Type Name="TB_CONTACTO">
      <Column Name="IdContacto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TB_CONTACTO_TB_USUARIO" Member="TB_USUARIOs" ThisKey="IdContacto" OtherKey="IdContacto" Type="TB_USUARIO" />
    </Type>
  </Table>
  <Table Name="dbo.TB_EDIFICIO" Member="TB_EDIFICIOs">
    <Type Name="TB_EDIFICIO">
      <Column Name="IdEdificio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoEdificio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CostoVenta" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TB_EDIFICIO_TB_EDIFICIO_RECURSO" Member="TB_EDIFICIO_RECURSOs" ThisKey="IdEdificio" OtherKey="IdEdificio" Type="TB_EDIFICIO_RECURSO" />
      <Association Name="TB_EDIFICIO_TB_LOG_EDIFICIO_USUARIO" Member="TB_LOG_EDIFICIO_USUARIOs" ThisKey="IdEdificio" OtherKey="IdEdificio" Type="TB_LOG_EDIFICIO_USUARIO" />
      <Association Name="TB_EDIFICIO_TB_PERSONAJE_EDIFICIO" Member="TB_PERSONAJE_EDIFICIOs" ThisKey="IdEdificio" OtherKey="IdEdificio" Type="TB_PERSONAJE_EDIFICIO" />
      <Association Name="TB_TIPO_EDIFICIO_TB_EDIFICIO" Member="TB_TIPO_EDIFICIO" ThisKey="IdTipoEdificio" OtherKey="IdTipoEdificio" Type="TB_TIPO_EDIFICIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_EDIFICIO_RECURSOS" Member="TB_EDIFICIO_RECURSOs">
    <Type Name="TB_EDIFICIO_RECURSO">
      <Column Name="IdEdificio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdRecurso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TB_EDIFICIO_TB_EDIFICIO_RECURSO" Member="TB_EDIFICIO" ThisKey="IdEdificio" OtherKey="IdEdificio" Type="TB_EDIFICIO" IsForeignKey="true" />
      <Association Name="TB_RECURSO_TB_EDIFICIO_RECURSO" Member="TB_RECURSO" ThisKey="IdRecurso" OtherKey="IdRecurso" Type="TB_RECURSO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_ESTADO_TX" Member="TB_ESTADO_TXes">
    <Type Name="TB_ESTADO_TX">
      <Column Name="IdEstado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TB_ESTADO_TX_TB_TX" Member="TB_TXes" ThisKey="IdEstado" OtherKey="IdEstadoTx" Type="TB_TX" />
    </Type>
  </Table>
  <Table Name="dbo.TB_LOG_EDIFICIO_USUARIO" Member="TB_LOG_EDIFICIO_USUARIOs">
    <Type Name="TB_LOG_EDIFICIO_USUARIO">
      <Column Name="IdLogEdificioUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdEdificio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUsuarioSistema" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TB_LOG_EDIFICIO_USUARIO_TB_TX" Member="TB_TXes" ThisKey="IdLogEdificioUsuario" OtherKey="IdLogEdificio" Type="TB_TX" />
      <Association Name="TB_EDIFICIO_TB_LOG_EDIFICIO_USUARIO" Member="TB_EDIFICIO" ThisKey="IdEdificio" OtherKey="IdEdificio" Type="TB_EDIFICIO" IsForeignKey="true" />
      <Association Name="TB_USUARIO_TB_LOG_EDIFICIO_USUARIO" Member="TB_USUARIO" ThisKey="IdUsuarioSistema" OtherKey="IdUsuario" Type="TB_USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_LOG_USUARIO_RECURSO" Member="TB_LOG_USUARIO_RECURSOs">
    <Type Name="TB_LOG_USUARIO_RECURSO">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdRecurso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TB_RECURSO_TB_LOG_USUARIO_RECURSO" Member="TB_RECURSO" ThisKey="IdRecurso" OtherKey="IdRecurso" Type="TB_RECURSO" IsForeignKey="true" />
      <Association Name="TB_USUARIO_TB_LOG_USUARIO_RECURSO" Member="TB_USUARIO" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="TB_USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_PERSONAJE" Member="TB_PERSONAJEs">
    <Type Name="TB_PERSONAJE">
      <Column Name="IdPersonaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdTipoPersonaje" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TB_PERSONAJE_TB_PERSONAJE_CARACTERISTICA" Member="TB_PERSONAJE_CARACTERISTICAs" ThisKey="IdPersonaje" OtherKey="IdPersonaje" Type="TB_PERSONAJE_CARACTERISTICA" />
      <Association Name="TB_PERSONAJE_TB_PERSONAJE_EDIFICIO" Member="TB_PERSONAJE_EDIFICIOs" ThisKey="IdPersonaje" OtherKey="IdPersonaje" Type="TB_PERSONAJE_EDIFICIO" />
      <Association Name="TB_PERSONAJE_TB_PERSONAJE_RECURSO" Member="TB_PERSONAJE_RECURSOs" ThisKey="IdPersonaje" OtherKey="IdPersonaje" Type="TB_PERSONAJE_RECURSO" />
      <Association Name="TB_TIPO_PERSONAJE_TB_PERSONAJE" Member="TB_TIPO_PERSONAJE" ThisKey="IdTipoPersonaje" OtherKey="IdTipoPersonaje" Type="TB_TIPO_PERSONAJE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_PERSONAJE_CARACTERISTICA" Member="TB_PERSONAJE_CARACTERISTICAs">
    <Type Name="TB_PERSONAJE_CARACTERISTICA">
      <Column Name="IdPersonaje" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCaracteristica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorCaracteristica" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TB_CARACTERISTICA_TB_PERSONAJE_CARACTERISTICA" Member="TB_CARACTERISTICA" ThisKey="IdCaracteristica" OtherKey="IdCaracteristicas" Type="TB_CARACTERISTICA" IsForeignKey="true" />
      <Association Name="TB_PERSONAJE_TB_PERSONAJE_CARACTERISTICA" Member="TB_PERSONAJE" ThisKey="IdPersonaje" OtherKey="IdPersonaje" Type="TB_PERSONAJE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_PERSONAJE_EDIFICIO" Member="TB_PERSONAJE_EDIFICIOs">
    <Type Name="TB_PERSONAJE_EDIFICIO">
      <Column Name="IdEdificio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdPersonaje" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TB_EDIFICIO_TB_PERSONAJE_EDIFICIO" Member="TB_EDIFICIO" ThisKey="IdEdificio" OtherKey="IdEdificio" Type="TB_EDIFICIO" IsForeignKey="true" />
      <Association Name="TB_PERSONAJE_TB_PERSONAJE_EDIFICIO" Member="TB_PERSONAJE" ThisKey="IdPersonaje" OtherKey="IdPersonaje" Type="TB_PERSONAJE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_PERSONAJE_RECURSO" Member="TB_PERSONAJE_RECURSOs">
    <Type Name="TB_PERSONAJE_RECURSO">
      <Column Name="IdPersonaje" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdRecurso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TB_PERSONAJE_TB_PERSONAJE_RECURSO" Member="TB_PERSONAJE" ThisKey="IdPersonaje" OtherKey="IdPersonaje" Type="TB_PERSONAJE" IsForeignKey="true" />
      <Association Name="TB_RECURSO_TB_PERSONAJE_RECURSO" Member="TB_RECURSO" ThisKey="IdRecurso" OtherKey="IdRecurso" Type="TB_RECURSO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_RECURSO" Member="TB_RECURSOs">
    <Type Name="TB_RECURSO">
      <Column Name="IdRecurso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdTipoRecurso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorUnidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Informcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TB_RECURSO_TB_EDIFICIO_RECURSO" Member="TB_EDIFICIO_RECURSOs" ThisKey="IdRecurso" OtherKey="IdRecurso" Type="TB_EDIFICIO_RECURSO" />
      <Association Name="TB_RECURSO_TB_LOG_USUARIO_RECURSO" Member="TB_LOG_USUARIO_RECURSOs" ThisKey="IdRecurso" OtherKey="IdRecurso" Type="TB_LOG_USUARIO_RECURSO" />
      <Association Name="TB_RECURSO_TB_PERSONAJE_RECURSO" Member="TB_PERSONAJE_RECURSOs" ThisKey="IdRecurso" OtherKey="IdRecurso" Type="TB_PERSONAJE_RECURSO" />
      <Association Name="TB_TIPO_RECURSO_TB_RECURSO" Member="TB_TIPO_RECURSO" ThisKey="IdTipoRecurso" OtherKey="IdTipoRecurso" Type="TB_TIPO_RECURSO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_TIPO_EDIFICIO" Member="TB_TIPO_EDIFICIOs">
    <Type Name="TB_TIPO_EDIFICIO">
      <Column Name="IdTipoEdificio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="Informacion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TB_TIPO_EDIFICIO_TB_EDIFICIO" Member="TB_EDIFICIOs" ThisKey="IdTipoEdificio" OtherKey="IdTipoEdificio" Type="TB_EDIFICIO" />
    </Type>
  </Table>
  <Table Name="dbo.TB_TIPO_PERSONAJE" Member="TB_TIPO_PERSONAJEs">
    <Type Name="TB_TIPO_PERSONAJE">
      <Column Name="IdTipoPersonaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="informacion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TB_TIPO_PERSONAJE_TB_PERSONAJE" Member="TB_PERSONAJEs" ThisKey="IdTipoPersonaje" OtherKey="IdTipoPersonaje" Type="TB_PERSONAJE" />
    </Type>
  </Table>
  <Table Name="dbo.TB_TIPO_RECURSO" Member="TB_TIPO_RECURSOs">
    <Type Name="TB_TIPO_RECURSO">
      <Column Name="IdTipoRecurso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TB_TIPO_RECURSO_TB_RECURSO" Member="TB_RECURSOs" ThisKey="IdTipoRecurso" OtherKey="IdTipoRecurso" Type="TB_RECURSO" />
    </Type>
  </Table>
  <Table Name="dbo.TB_TIPO_TX" Member="TB_TIPO_TXes">
    <Type Name="TB_TIPO_TX">
      <Column Name="IdTipoTx" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TB_TIPO_TX_TB_TX" Member="TB_TXes" ThisKey="IdTipoTx" OtherKey="IdTipoTX" Type="TB_TX" />
    </Type>
  </Table>
  <Table Name="dbo.TB_TX" Member="TB_TXes">
    <Type Name="TB_TX">
      <Column Name="IdTx" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdLogEdificio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdTipoTX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEstadoTx" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaTx" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TB_ESTADO_TX_TB_TX" Member="TB_ESTADO_TX" ThisKey="IdEstadoTx" OtherKey="IdEstado" Type="TB_ESTADO_TX" IsForeignKey="true" />
      <Association Name="TB_LOG_EDIFICIO_USUARIO_TB_TX" Member="TB_LOG_EDIFICIO_USUARIO" ThisKey="IdLogEdificio" OtherKey="IdLogEdificioUsuario" Type="TB_LOG_EDIFICIO_USUARIO" IsForeignKey="true" />
      <Association Name="TB_TIPO_TX_TB_TX" Member="TB_TIPO_TX" ThisKey="IdTipoTX" OtherKey="IdTipoTx" Type="TB_TIPO_TX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_USUARIO" Member="TB_USUARIOs">
    <Type Name="TB_USUARIO" Id="ID1">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdContacto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Clave" Type="System.Data.Linq.Binary" DbType="VarBinary(46)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TB_USUARIO_TB_LOG_EDIFICIO_USUARIO" Member="TB_LOG_EDIFICIO_USUARIOs" ThisKey="IdUsuario" OtherKey="IdUsuarioSistema" Type="TB_LOG_EDIFICIO_USUARIO" />
      <Association Name="TB_USUARIO_TB_LOG_USUARIO_RECURSO" Member="TB_LOG_USUARIO_RECURSOs" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="TB_LOG_USUARIO_RECURSO" />
      <Association Name="TB_CONTACTO_TB_USUARIO" Member="TB_CONTACTO" ThisKey="IdContacto" OtherKey="IdContacto" Type="TB_CONTACTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.InsertUser" Method="InsertUser">
    <Parameter Name="IdContact" Parameter="idContact" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NameUser" Parameter="nameUser" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertContact" Method="InsertContact">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Surname" Parameter="surname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdContacto" Parameter="idContacto" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetUser" Method="GetUser">
    <Parameter Name="NameUser" Parameter="nameUser" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>