#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SpaceAppChallenge")]
	public partial class DataAccessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_CARACTERISTICA(TB_CARACTERISTICA instance);
    partial void UpdateTB_CARACTERISTICA(TB_CARACTERISTICA instance);
    partial void DeleteTB_CARACTERISTICA(TB_CARACTERISTICA instance);
    partial void InsertTB_CONTACTO(TB_CONTACTO instance);
    partial void UpdateTB_CONTACTO(TB_CONTACTO instance);
    partial void DeleteTB_CONTACTO(TB_CONTACTO instance);
    partial void InsertTB_EDIFICIO(TB_EDIFICIO instance);
    partial void UpdateTB_EDIFICIO(TB_EDIFICIO instance);
    partial void DeleteTB_EDIFICIO(TB_EDIFICIO instance);
    partial void InsertTB_ESTADO_TX(TB_ESTADO_TX instance);
    partial void UpdateTB_ESTADO_TX(TB_ESTADO_TX instance);
    partial void DeleteTB_ESTADO_TX(TB_ESTADO_TX instance);
    partial void InsertTB_LOG_EDIFICIO_USUARIO(TB_LOG_EDIFICIO_USUARIO instance);
    partial void UpdateTB_LOG_EDIFICIO_USUARIO(TB_LOG_EDIFICIO_USUARIO instance);
    partial void DeleteTB_LOG_EDIFICIO_USUARIO(TB_LOG_EDIFICIO_USUARIO instance);
    partial void InsertTB_PERSONAJE(TB_PERSONAJE instance);
    partial void UpdateTB_PERSONAJE(TB_PERSONAJE instance);
    partial void DeleteTB_PERSONAJE(TB_PERSONAJE instance);
    partial void InsertTB_PERSONAJE_EDIFICIO(TB_PERSONAJE_EDIFICIO instance);
    partial void UpdateTB_PERSONAJE_EDIFICIO(TB_PERSONAJE_EDIFICIO instance);
    partial void DeleteTB_PERSONAJE_EDIFICIO(TB_PERSONAJE_EDIFICIO instance);
    partial void InsertTB_RECURSO(TB_RECURSO instance);
    partial void UpdateTB_RECURSO(TB_RECURSO instance);
    partial void DeleteTB_RECURSO(TB_RECURSO instance);
    partial void InsertTB_TIPO_EDIFICIO(TB_TIPO_EDIFICIO instance);
    partial void UpdateTB_TIPO_EDIFICIO(TB_TIPO_EDIFICIO instance);
    partial void DeleteTB_TIPO_EDIFICIO(TB_TIPO_EDIFICIO instance);
    partial void InsertTB_TIPO_PERSONAJE(TB_TIPO_PERSONAJE instance);
    partial void UpdateTB_TIPO_PERSONAJE(TB_TIPO_PERSONAJE instance);
    partial void DeleteTB_TIPO_PERSONAJE(TB_TIPO_PERSONAJE instance);
    partial void InsertTB_TIPO_RECURSO(TB_TIPO_RECURSO instance);
    partial void UpdateTB_TIPO_RECURSO(TB_TIPO_RECURSO instance);
    partial void DeleteTB_TIPO_RECURSO(TB_TIPO_RECURSO instance);
    partial void InsertTB_TIPO_TX(TB_TIPO_TX instance);
    partial void UpdateTB_TIPO_TX(TB_TIPO_TX instance);
    partial void DeleteTB_TIPO_TX(TB_TIPO_TX instance);
    partial void InsertTB_TX(TB_TX instance);
    partial void UpdateTB_TX(TB_TX instance);
    partial void DeleteTB_TX(TB_TX instance);
    partial void InsertTB_USUARIO(TB_USUARIO instance);
    partial void UpdateTB_USUARIO(TB_USUARIO instance);
    partial void DeleteTB_USUARIO(TB_USUARIO instance);
    #endregion
		
		public DataAccessDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.SpaceAppChallengeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_CARACTERISTICA> TB_CARACTERISTICAs
		{
			get
			{
				return this.GetTable<TB_CARACTERISTICA>();
			}
		}
		
		public System.Data.Linq.Table<TB_CONTACTO> TB_CONTACTOs
		{
			get
			{
				return this.GetTable<TB_CONTACTO>();
			}
		}
		
		public System.Data.Linq.Table<TB_EDIFICIO> TB_EDIFICIOs
		{
			get
			{
				return this.GetTable<TB_EDIFICIO>();
			}
		}
		
		public System.Data.Linq.Table<TB_EDIFICIO_RECURSO> TB_EDIFICIO_RECURSOs
		{
			get
			{
				return this.GetTable<TB_EDIFICIO_RECURSO>();
			}
		}
		
		public System.Data.Linq.Table<TB_ESTADO_TX> TB_ESTADO_TXes
		{
			get
			{
				return this.GetTable<TB_ESTADO_TX>();
			}
		}
		
		public System.Data.Linq.Table<TB_LOG_EDIFICIO_USUARIO> TB_LOG_EDIFICIO_USUARIOs
		{
			get
			{
				return this.GetTable<TB_LOG_EDIFICIO_USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<TB_LOG_USUARIO_RECURSO> TB_LOG_USUARIO_RECURSOs
		{
			get
			{
				return this.GetTable<TB_LOG_USUARIO_RECURSO>();
			}
		}
		
		public System.Data.Linq.Table<TB_PERSONAJE> TB_PERSONAJEs
		{
			get
			{
				return this.GetTable<TB_PERSONAJE>();
			}
		}
		
		public System.Data.Linq.Table<TB_PERSONAJE_CARACTERISTICA> TB_PERSONAJE_CARACTERISTICAs
		{
			get
			{
				return this.GetTable<TB_PERSONAJE_CARACTERISTICA>();
			}
		}
		
		public System.Data.Linq.Table<TB_PERSONAJE_EDIFICIO> TB_PERSONAJE_EDIFICIOs
		{
			get
			{
				return this.GetTable<TB_PERSONAJE_EDIFICIO>();
			}
		}
		
		public System.Data.Linq.Table<TB_PERSONAJE_RECURSO> TB_PERSONAJE_RECURSOs
		{
			get
			{
				return this.GetTable<TB_PERSONAJE_RECURSO>();
			}
		}
		
		public System.Data.Linq.Table<TB_RECURSO> TB_RECURSOs
		{
			get
			{
				return this.GetTable<TB_RECURSO>();
			}
		}
		
		public System.Data.Linq.Table<TB_TIPO_EDIFICIO> TB_TIPO_EDIFICIOs
		{
			get
			{
				return this.GetTable<TB_TIPO_EDIFICIO>();
			}
		}
		
		public System.Data.Linq.Table<TB_TIPO_PERSONAJE> TB_TIPO_PERSONAJEs
		{
			get
			{
				return this.GetTable<TB_TIPO_PERSONAJE>();
			}
		}
		
		public System.Data.Linq.Table<TB_TIPO_RECURSO> TB_TIPO_RECURSOs
		{
			get
			{
				return this.GetTable<TB_TIPO_RECURSO>();
			}
		}
		
		public System.Data.Linq.Table<TB_TIPO_TX> TB_TIPO_TXes
		{
			get
			{
				return this.GetTable<TB_TIPO_TX>();
			}
		}
		
		public System.Data.Linq.Table<TB_TX> TB_TXes
		{
			get
			{
				return this.GetTable<TB_TX>();
			}
		}
		
		public System.Data.Linq.Table<TB_USUARIO> TB_USUARIOs
		{
			get
			{
				return this.GetTable<TB_USUARIO>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertUser")]
		public int InsertUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContact", DbType="VarChar(50)")] string idContact, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NameUser", DbType="VarChar(50)")] string nameUser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContact, nameUser, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertContact")]
		public int InsertContact([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Surname", DbType="VarChar(50)")] string surname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContacto", DbType="Int")] ref System.Nullable<int> idContacto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, surname, email, idContacto);
			idContacto = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUser")]
		public ISingleResult<TB_USUARIO> GetUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NameUser", DbType="VarChar(50)")] string nameUser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nameUser, password);
			return ((ISingleResult<TB_USUARIO>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CARACTERISTICAS")]
	public partial class TB_CARACTERISTICA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCaracteristicas;
		
		private string _Descripcion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCaracteristicasChanging(int value);
    partial void OnIdCaracteristicasChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public TB_CARACTERISTICA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaracteristicas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCaracteristicas
		{
			get
			{
				return this._IdCaracteristicas;
			}
			set
			{
				if ((this._IdCaracteristicas != value))
				{
					this.OnIdCaracteristicasChanging(value);
					this.SendPropertyChanging();
					this._IdCaracteristicas = value;
					this.SendPropertyChanged("IdCaracteristicas");
					this.OnIdCaracteristicasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CONTACTO")]
	public partial class TB_CONTACTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdContacto;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Correo;
		
		private EntitySet<TB_USUARIO> _TB_USUARIOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdContactoChanging(int value);
    partial void OnIdContactoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    #endregion
		
		public TB_CONTACTO()
		{
			this._TB_USUARIOs = new EntitySet<TB_USUARIO>(new Action<TB_USUARIO>(this.attach_TB_USUARIOs), new Action<TB_USUARIO>(this.detach_TB_USUARIOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContacto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdContacto
		{
			get
			{
				return this._IdContacto;
			}
			set
			{
				if ((this._IdContacto != value))
				{
					this.OnIdContactoChanging(value);
					this.SendPropertyChanging();
					this._IdContacto = value;
					this.SendPropertyChanged("IdContacto");
					this.OnIdContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CONTACTO_TB_USUARIO", Storage="_TB_USUARIOs", ThisKey="IdContacto", OtherKey="IdContacto")]
		public EntitySet<TB_USUARIO> TB_USUARIOs
		{
			get
			{
				return this._TB_USUARIOs;
			}
			set
			{
				this._TB_USUARIOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_USUARIOs(TB_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_CONTACTO = this;
		}
		
		private void detach_TB_USUARIOs(TB_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_CONTACTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_EDIFICIO")]
	public partial class TB_EDIFICIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEdificio;
		
		private System.Nullable<int> _IdPadre;
		
		private System.Nullable<int> _IdTipoEdificio;
		
		private System.Nullable<decimal> _CostoVenta;
		
		private string _Descripcion;
		
		private EntitySet<TB_LOG_EDIFICIO_USUARIO> _TB_LOG_EDIFICIO_USUARIOs;
		
		private EntitySet<TB_PERSONAJE_EDIFICIO> _TB_PERSONAJE_EDIFICIOs;
		
		private EntityRef<TB_TIPO_EDIFICIO> _TB_TIPO_EDIFICIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEdificioChanging(int value);
    partial void OnIdEdificioChanged();
    partial void OnIdPadreChanging(System.Nullable<int> value);
    partial void OnIdPadreChanged();
    partial void OnIdTipoEdificioChanging(System.Nullable<int> value);
    partial void OnIdTipoEdificioChanged();
    partial void OnCostoVentaChanging(System.Nullable<decimal> value);
    partial void OnCostoVentaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public TB_EDIFICIO()
		{
			this._TB_LOG_EDIFICIO_USUARIOs = new EntitySet<TB_LOG_EDIFICIO_USUARIO>(new Action<TB_LOG_EDIFICIO_USUARIO>(this.attach_TB_LOG_EDIFICIO_USUARIOs), new Action<TB_LOG_EDIFICIO_USUARIO>(this.detach_TB_LOG_EDIFICIO_USUARIOs));
			this._TB_PERSONAJE_EDIFICIOs = new EntitySet<TB_PERSONAJE_EDIFICIO>(new Action<TB_PERSONAJE_EDIFICIO>(this.attach_TB_PERSONAJE_EDIFICIOs), new Action<TB_PERSONAJE_EDIFICIO>(this.detach_TB_PERSONAJE_EDIFICIOs));
			this._TB_TIPO_EDIFICIO = default(EntityRef<TB_TIPO_EDIFICIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEdificio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEdificio
		{
			get
			{
				return this._IdEdificio;
			}
			set
			{
				if ((this._IdEdificio != value))
				{
					this.OnIdEdificioChanging(value);
					this.SendPropertyChanging();
					this._IdEdificio = value;
					this.SendPropertyChanged("IdEdificio");
					this.OnIdEdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPadre", DbType="Int")]
		public System.Nullable<int> IdPadre
		{
			get
			{
				return this._IdPadre;
			}
			set
			{
				if ((this._IdPadre != value))
				{
					this.OnIdPadreChanging(value);
					this.SendPropertyChanging();
					this._IdPadre = value;
					this.SendPropertyChanged("IdPadre");
					this.OnIdPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEdificio", DbType="Int")]
		public System.Nullable<int> IdTipoEdificio
		{
			get
			{
				return this._IdTipoEdificio;
			}
			set
			{
				if ((this._IdTipoEdificio != value))
				{
					if (this._TB_TIPO_EDIFICIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoEdificioChanging(value);
					this.SendPropertyChanging();
					this._IdTipoEdificio = value;
					this.SendPropertyChanged("IdTipoEdificio");
					this.OnIdTipoEdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoVenta", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CostoVenta
		{
			get
			{
				return this._CostoVenta;
			}
			set
			{
				if ((this._CostoVenta != value))
				{
					this.OnCostoVentaChanging(value);
					this.SendPropertyChanging();
					this._CostoVenta = value;
					this.SendPropertyChanged("CostoVenta");
					this.OnCostoVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_EDIFICIO_TB_LOG_EDIFICIO_USUARIO", Storage="_TB_LOG_EDIFICIO_USUARIOs", ThisKey="IdEdificio", OtherKey="IdEdificio")]
		public EntitySet<TB_LOG_EDIFICIO_USUARIO> TB_LOG_EDIFICIO_USUARIOs
		{
			get
			{
				return this._TB_LOG_EDIFICIO_USUARIOs;
			}
			set
			{
				this._TB_LOG_EDIFICIO_USUARIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_EDIFICIO_TB_PERSONAJE_EDIFICIO", Storage="_TB_PERSONAJE_EDIFICIOs", ThisKey="IdEdificio", OtherKey="IdEdificio")]
		public EntitySet<TB_PERSONAJE_EDIFICIO> TB_PERSONAJE_EDIFICIOs
		{
			get
			{
				return this._TB_PERSONAJE_EDIFICIOs;
			}
			set
			{
				this._TB_PERSONAJE_EDIFICIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_TIPO_EDIFICIO_TB_EDIFICIO", Storage="_TB_TIPO_EDIFICIO", ThisKey="IdTipoEdificio", OtherKey="IdTipoEdificio", IsForeignKey=true)]
		public TB_TIPO_EDIFICIO TB_TIPO_EDIFICIO
		{
			get
			{
				return this._TB_TIPO_EDIFICIO.Entity;
			}
			set
			{
				TB_TIPO_EDIFICIO previousValue = this._TB_TIPO_EDIFICIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_TIPO_EDIFICIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_TIPO_EDIFICIO.Entity = null;
						previousValue.TB_EDIFICIOs.Remove(this);
					}
					this._TB_TIPO_EDIFICIO.Entity = value;
					if ((value != null))
					{
						value.TB_EDIFICIOs.Add(this);
						this._IdTipoEdificio = value.IdTipoEdificio;
					}
					else
					{
						this._IdTipoEdificio = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_TIPO_EDIFICIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_LOG_EDIFICIO_USUARIOs(TB_LOG_EDIFICIO_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_EDIFICIO = this;
		}
		
		private void detach_TB_LOG_EDIFICIO_USUARIOs(TB_LOG_EDIFICIO_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_EDIFICIO = null;
		}
		
		private void attach_TB_PERSONAJE_EDIFICIOs(TB_PERSONAJE_EDIFICIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_EDIFICIO = this;
		}
		
		private void detach_TB_PERSONAJE_EDIFICIOs(TB_PERSONAJE_EDIFICIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_EDIFICIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_EDIFICIO_RECURSOS")]
	public partial class TB_EDIFICIO_RECURSO
	{
		
		private System.Nullable<int> _IdEdificio;
		
		private System.Nullable<int> _IdRecurso;
		
		private System.Nullable<int> _Cantidad;
		
		public TB_EDIFICIO_RECURSO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEdificio", DbType="Int")]
		public System.Nullable<int> IdEdificio
		{
			get
			{
				return this._IdEdificio;
			}
			set
			{
				if ((this._IdEdificio != value))
				{
					this._IdEdificio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRecurso", DbType="Int")]
		public System.Nullable<int> IdRecurso
		{
			get
			{
				return this._IdRecurso;
			}
			set
			{
				if ((this._IdRecurso != value))
				{
					this._IdRecurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_ESTADO_TX")]
	public partial class TB_ESTADO_TX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEstado;
		
		private string _Descripcion;
		
		private EntitySet<TB_TX> _TB_TXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstadoChanging(int value);
    partial void OnIdEstadoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public TB_ESTADO_TX()
		{
			this._TB_TXes = new EntitySet<TB_TX>(new Action<TB_TX>(this.attach_TB_TXes), new Action<TB_TX>(this.detach_TB_TXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_ESTADO_TX_TB_TX", Storage="_TB_TXes", ThisKey="IdEstado", OtherKey="IdEstadoTx")]
		public EntitySet<TB_TX> TB_TXes
		{
			get
			{
				return this._TB_TXes;
			}
			set
			{
				this._TB_TXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_TXes(TB_TX entity)
		{
			this.SendPropertyChanging();
			entity.TB_ESTADO_TX = this;
		}
		
		private void detach_TB_TXes(TB_TX entity)
		{
			this.SendPropertyChanging();
			entity.TB_ESTADO_TX = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_LOG_EDIFICIO_USUARIO")]
	public partial class TB_LOG_EDIFICIO_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLogEdificioUsuario;
		
		private System.Nullable<int> _IdEdificio;
		
		private System.Nullable<int> _IdUsuarioSistema;
		
		private EntitySet<TB_TX> _TB_TXes;
		
		private EntityRef<TB_EDIFICIO> _TB_EDIFICIO;
		
		private EntityRef<TB_USUARIO> _TB_USUARIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLogEdificioUsuarioChanging(int value);
    partial void OnIdLogEdificioUsuarioChanged();
    partial void OnIdEdificioChanging(System.Nullable<int> value);
    partial void OnIdEdificioChanged();
    partial void OnIdUsuarioSistemaChanging(System.Nullable<int> value);
    partial void OnIdUsuarioSistemaChanged();
    #endregion
		
		public TB_LOG_EDIFICIO_USUARIO()
		{
			this._TB_TXes = new EntitySet<TB_TX>(new Action<TB_TX>(this.attach_TB_TXes), new Action<TB_TX>(this.detach_TB_TXes));
			this._TB_EDIFICIO = default(EntityRef<TB_EDIFICIO>);
			this._TB_USUARIO = default(EntityRef<TB_USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLogEdificioUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdLogEdificioUsuario
		{
			get
			{
				return this._IdLogEdificioUsuario;
			}
			set
			{
				if ((this._IdLogEdificioUsuario != value))
				{
					this.OnIdLogEdificioUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdLogEdificioUsuario = value;
					this.SendPropertyChanged("IdLogEdificioUsuario");
					this.OnIdLogEdificioUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEdificio", DbType="Int")]
		public System.Nullable<int> IdEdificio
		{
			get
			{
				return this._IdEdificio;
			}
			set
			{
				if ((this._IdEdificio != value))
				{
					if (this._TB_EDIFICIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEdificioChanging(value);
					this.SendPropertyChanging();
					this._IdEdificio = value;
					this.SendPropertyChanged("IdEdificio");
					this.OnIdEdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioSistema", DbType="Int")]
		public System.Nullable<int> IdUsuarioSistema
		{
			get
			{
				return this._IdUsuarioSistema;
			}
			set
			{
				if ((this._IdUsuarioSistema != value))
				{
					if (this._TB_USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioSistemaChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioSistema = value;
					this.SendPropertyChanged("IdUsuarioSistema");
					this.OnIdUsuarioSistemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_LOG_EDIFICIO_USUARIO_TB_TX", Storage="_TB_TXes", ThisKey="IdLogEdificioUsuario", OtherKey="IdLogEdificio")]
		public EntitySet<TB_TX> TB_TXes
		{
			get
			{
				return this._TB_TXes;
			}
			set
			{
				this._TB_TXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_EDIFICIO_TB_LOG_EDIFICIO_USUARIO", Storage="_TB_EDIFICIO", ThisKey="IdEdificio", OtherKey="IdEdificio", IsForeignKey=true)]
		public TB_EDIFICIO TB_EDIFICIO
		{
			get
			{
				return this._TB_EDIFICIO.Entity;
			}
			set
			{
				TB_EDIFICIO previousValue = this._TB_EDIFICIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_EDIFICIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_EDIFICIO.Entity = null;
						previousValue.TB_LOG_EDIFICIO_USUARIOs.Remove(this);
					}
					this._TB_EDIFICIO.Entity = value;
					if ((value != null))
					{
						value.TB_LOG_EDIFICIO_USUARIOs.Add(this);
						this._IdEdificio = value.IdEdificio;
					}
					else
					{
						this._IdEdificio = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_EDIFICIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_USUARIO_TB_LOG_EDIFICIO_USUARIO", Storage="_TB_USUARIO", ThisKey="IdUsuarioSistema", OtherKey="IdUsuario", IsForeignKey=true)]
		public TB_USUARIO TB_USUARIO
		{
			get
			{
				return this._TB_USUARIO.Entity;
			}
			set
			{
				TB_USUARIO previousValue = this._TB_USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_USUARIO.Entity = null;
						previousValue.TB_LOG_EDIFICIO_USUARIOs.Remove(this);
					}
					this._TB_USUARIO.Entity = value;
					if ((value != null))
					{
						value.TB_LOG_EDIFICIO_USUARIOs.Add(this);
						this._IdUsuarioSistema = value.IdUsuario;
					}
					else
					{
						this._IdUsuarioSistema = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_USUARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_TXes(TB_TX entity)
		{
			this.SendPropertyChanging();
			entity.TB_LOG_EDIFICIO_USUARIO = this;
		}
		
		private void detach_TB_TXes(TB_TX entity)
		{
			this.SendPropertyChanging();
			entity.TB_LOG_EDIFICIO_USUARIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_LOG_USUARIO_RECURSO")]
	public partial class TB_LOG_USUARIO_RECURSO
	{
		
		private System.Nullable<int> _IdUsuario;
		
		private System.Nullable<int> _IdRecurso;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		public TB_LOG_USUARIO_RECURSO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRecurso", DbType="Int")]
		public System.Nullable<int> IdRecurso
		{
			get
			{
				return this._IdRecurso;
			}
			set
			{
				if ((this._IdRecurso != value))
				{
					this._IdRecurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PERSONAJE")]
	public partial class TB_PERSONAJE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPersonaje;
		
		private System.Nullable<int> _IdTipoPersonaje;
		
		private string _Descripcion;
		
		private EntitySet<TB_PERSONAJE_EDIFICIO> _TB_PERSONAJE_EDIFICIOs;
		
		private EntityRef<TB_TIPO_PERSONAJE> _TB_TIPO_PERSONAJE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPersonajeChanging(int value);
    partial void OnIdPersonajeChanged();
    partial void OnIdTipoPersonajeChanging(System.Nullable<int> value);
    partial void OnIdTipoPersonajeChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public TB_PERSONAJE()
		{
			this._TB_PERSONAJE_EDIFICIOs = new EntitySet<TB_PERSONAJE_EDIFICIO>(new Action<TB_PERSONAJE_EDIFICIO>(this.attach_TB_PERSONAJE_EDIFICIOs), new Action<TB_PERSONAJE_EDIFICIO>(this.detach_TB_PERSONAJE_EDIFICIOs));
			this._TB_TIPO_PERSONAJE = default(EntityRef<TB_TIPO_PERSONAJE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersonaje", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPersonaje
		{
			get
			{
				return this._IdPersonaje;
			}
			set
			{
				if ((this._IdPersonaje != value))
				{
					this.OnIdPersonajeChanging(value);
					this.SendPropertyChanging();
					this._IdPersonaje = value;
					this.SendPropertyChanged("IdPersonaje");
					this.OnIdPersonajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPersonaje", DbType="Int")]
		public System.Nullable<int> IdTipoPersonaje
		{
			get
			{
				return this._IdTipoPersonaje;
			}
			set
			{
				if ((this._IdTipoPersonaje != value))
				{
					if (this._TB_TIPO_PERSONAJE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoPersonajeChanging(value);
					this.SendPropertyChanging();
					this._IdTipoPersonaje = value;
					this.SendPropertyChanged("IdTipoPersonaje");
					this.OnIdTipoPersonajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_PERSONAJE_TB_PERSONAJE_EDIFICIO", Storage="_TB_PERSONAJE_EDIFICIOs", ThisKey="IdPersonaje", OtherKey="IdPersonaje")]
		public EntitySet<TB_PERSONAJE_EDIFICIO> TB_PERSONAJE_EDIFICIOs
		{
			get
			{
				return this._TB_PERSONAJE_EDIFICIOs;
			}
			set
			{
				this._TB_PERSONAJE_EDIFICIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_TIPO_PERSONAJE_TB_PERSONAJE", Storage="_TB_TIPO_PERSONAJE", ThisKey="IdTipoPersonaje", OtherKey="IdTipoPersonaje", IsForeignKey=true)]
		public TB_TIPO_PERSONAJE TB_TIPO_PERSONAJE
		{
			get
			{
				return this._TB_TIPO_PERSONAJE.Entity;
			}
			set
			{
				TB_TIPO_PERSONAJE previousValue = this._TB_TIPO_PERSONAJE.Entity;
				if (((previousValue != value) 
							|| (this._TB_TIPO_PERSONAJE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_TIPO_PERSONAJE.Entity = null;
						previousValue.TB_PERSONAJEs.Remove(this);
					}
					this._TB_TIPO_PERSONAJE.Entity = value;
					if ((value != null))
					{
						value.TB_PERSONAJEs.Add(this);
						this._IdTipoPersonaje = value.IdTipoPersonaje;
					}
					else
					{
						this._IdTipoPersonaje = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_TIPO_PERSONAJE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_PERSONAJE_EDIFICIOs(TB_PERSONAJE_EDIFICIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_PERSONAJE = this;
		}
		
		private void detach_TB_PERSONAJE_EDIFICIOs(TB_PERSONAJE_EDIFICIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_PERSONAJE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PERSONAJE_CARACTERISTICA")]
	public partial class TB_PERSONAJE_CARACTERISTICA
	{
		
		private System.Nullable<int> _IdPersonaje;
		
		private System.Nullable<int> _IdCaracteristica;
		
		private string _ValorCaracteristica;
		
		public TB_PERSONAJE_CARACTERISTICA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersonaje", DbType="Int")]
		public System.Nullable<int> IdPersonaje
		{
			get
			{
				return this._IdPersonaje;
			}
			set
			{
				if ((this._IdPersonaje != value))
				{
					this._IdPersonaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaracteristica", DbType="Int")]
		public System.Nullable<int> IdCaracteristica
		{
			get
			{
				return this._IdCaracteristica;
			}
			set
			{
				if ((this._IdCaracteristica != value))
				{
					this._IdCaracteristica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorCaracteristica", DbType="VarChar(50)")]
		public string ValorCaracteristica
		{
			get
			{
				return this._ValorCaracteristica;
			}
			set
			{
				if ((this._ValorCaracteristica != value))
				{
					this._ValorCaracteristica = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PERSONAJE_EDIFICIO")]
	public partial class TB_PERSONAJE_EDIFICIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEdificio;
		
		private int _IdPersonaje;
		
		private EntityRef<TB_EDIFICIO> _TB_EDIFICIO;
		
		private EntityRef<TB_PERSONAJE> _TB_PERSONAJE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEdificioChanging(int value);
    partial void OnIdEdificioChanged();
    partial void OnIdPersonajeChanging(int value);
    partial void OnIdPersonajeChanged();
    #endregion
		
		public TB_PERSONAJE_EDIFICIO()
		{
			this._TB_EDIFICIO = default(EntityRef<TB_EDIFICIO>);
			this._TB_PERSONAJE = default(EntityRef<TB_PERSONAJE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEdificio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdEdificio
		{
			get
			{
				return this._IdEdificio;
			}
			set
			{
				if ((this._IdEdificio != value))
				{
					if (this._TB_EDIFICIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEdificioChanging(value);
					this.SendPropertyChanging();
					this._IdEdificio = value;
					this.SendPropertyChanged("IdEdificio");
					this.OnIdEdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersonaje", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPersonaje
		{
			get
			{
				return this._IdPersonaje;
			}
			set
			{
				if ((this._IdPersonaje != value))
				{
					if (this._TB_PERSONAJE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPersonajeChanging(value);
					this.SendPropertyChanging();
					this._IdPersonaje = value;
					this.SendPropertyChanged("IdPersonaje");
					this.OnIdPersonajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_EDIFICIO_TB_PERSONAJE_EDIFICIO", Storage="_TB_EDIFICIO", ThisKey="IdEdificio", OtherKey="IdEdificio", IsForeignKey=true)]
		public TB_EDIFICIO TB_EDIFICIO
		{
			get
			{
				return this._TB_EDIFICIO.Entity;
			}
			set
			{
				TB_EDIFICIO previousValue = this._TB_EDIFICIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_EDIFICIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_EDIFICIO.Entity = null;
						previousValue.TB_PERSONAJE_EDIFICIOs.Remove(this);
					}
					this._TB_EDIFICIO.Entity = value;
					if ((value != null))
					{
						value.TB_PERSONAJE_EDIFICIOs.Add(this);
						this._IdEdificio = value.IdEdificio;
					}
					else
					{
						this._IdEdificio = default(int);
					}
					this.SendPropertyChanged("TB_EDIFICIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_PERSONAJE_TB_PERSONAJE_EDIFICIO", Storage="_TB_PERSONAJE", ThisKey="IdPersonaje", OtherKey="IdPersonaje", IsForeignKey=true)]
		public TB_PERSONAJE TB_PERSONAJE
		{
			get
			{
				return this._TB_PERSONAJE.Entity;
			}
			set
			{
				TB_PERSONAJE previousValue = this._TB_PERSONAJE.Entity;
				if (((previousValue != value) 
							|| (this._TB_PERSONAJE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_PERSONAJE.Entity = null;
						previousValue.TB_PERSONAJE_EDIFICIOs.Remove(this);
					}
					this._TB_PERSONAJE.Entity = value;
					if ((value != null))
					{
						value.TB_PERSONAJE_EDIFICIOs.Add(this);
						this._IdPersonaje = value.IdPersonaje;
					}
					else
					{
						this._IdPersonaje = default(int);
					}
					this.SendPropertyChanged("TB_PERSONAJE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PERSONAJE_RECURSO")]
	public partial class TB_PERSONAJE_RECURSO
	{
		
		private System.Nullable<int> _IdPersonaje;
		
		private System.Nullable<int> _IdRecurso;
		
		private System.Nullable<int> _Cantidad;
		
		public TB_PERSONAJE_RECURSO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersonaje", DbType="Int")]
		public System.Nullable<int> IdPersonaje
		{
			get
			{
				return this._IdPersonaje;
			}
			set
			{
				if ((this._IdPersonaje != value))
				{
					this._IdPersonaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRecurso", DbType="Int")]
		public System.Nullable<int> IdRecurso
		{
			get
			{
				return this._IdRecurso;
			}
			set
			{
				if ((this._IdRecurso != value))
				{
					this._IdRecurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_RECURSO")]
	public partial class TB_RECURSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRecurso;
		
		private System.Nullable<int> _IdTipoRecurso;
		
		private System.Nullable<int> _ValorUnidad;
		
		private string _Informcion;
		
		private EntityRef<TB_TIPO_RECURSO> _TB_TIPO_RECURSO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRecursoChanging(int value);
    partial void OnIdRecursoChanged();
    partial void OnIdTipoRecursoChanging(System.Nullable<int> value);
    partial void OnIdTipoRecursoChanged();
    partial void OnValorUnidadChanging(System.Nullable<int> value);
    partial void OnValorUnidadChanged();
    partial void OnInformcionChanging(string value);
    partial void OnInformcionChanged();
    #endregion
		
		public TB_RECURSO()
		{
			this._TB_TIPO_RECURSO = default(EntityRef<TB_TIPO_RECURSO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRecurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdRecurso
		{
			get
			{
				return this._IdRecurso;
			}
			set
			{
				if ((this._IdRecurso != value))
				{
					this.OnIdRecursoChanging(value);
					this.SendPropertyChanging();
					this._IdRecurso = value;
					this.SendPropertyChanged("IdRecurso");
					this.OnIdRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoRecurso", DbType="Int")]
		public System.Nullable<int> IdTipoRecurso
		{
			get
			{
				return this._IdTipoRecurso;
			}
			set
			{
				if ((this._IdTipoRecurso != value))
				{
					if (this._TB_TIPO_RECURSO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoRecursoChanging(value);
					this.SendPropertyChanging();
					this._IdTipoRecurso = value;
					this.SendPropertyChanged("IdTipoRecurso");
					this.OnIdTipoRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorUnidad", DbType="Int")]
		public System.Nullable<int> ValorUnidad
		{
			get
			{
				return this._ValorUnidad;
			}
			set
			{
				if ((this._ValorUnidad != value))
				{
					this.OnValorUnidadChanging(value);
					this.SendPropertyChanging();
					this._ValorUnidad = value;
					this.SendPropertyChanged("ValorUnidad");
					this.OnValorUnidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Informcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Informcion
		{
			get
			{
				return this._Informcion;
			}
			set
			{
				if ((this._Informcion != value))
				{
					this.OnInformcionChanging(value);
					this.SendPropertyChanging();
					this._Informcion = value;
					this.SendPropertyChanged("Informcion");
					this.OnInformcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_TIPO_RECURSO_TB_RECURSO", Storage="_TB_TIPO_RECURSO", ThisKey="IdTipoRecurso", OtherKey="IdTipoRecurso", IsForeignKey=true)]
		public TB_TIPO_RECURSO TB_TIPO_RECURSO
		{
			get
			{
				return this._TB_TIPO_RECURSO.Entity;
			}
			set
			{
				TB_TIPO_RECURSO previousValue = this._TB_TIPO_RECURSO.Entity;
				if (((previousValue != value) 
							|| (this._TB_TIPO_RECURSO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_TIPO_RECURSO.Entity = null;
						previousValue.TB_RECURSOs.Remove(this);
					}
					this._TB_TIPO_RECURSO.Entity = value;
					if ((value != null))
					{
						value.TB_RECURSOs.Add(this);
						this._IdTipoRecurso = value.IdTipoRecurso;
					}
					else
					{
						this._IdTipoRecurso = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_TIPO_RECURSO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_TIPO_EDIFICIO")]
	public partial class TB_TIPO_EDIFICIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTipoEdificio;
		
		private string _Descripcion;
		
		private string _Informacion;
		
		private EntitySet<TB_EDIFICIO> _TB_EDIFICIOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTipoEdificioChanging(int value);
    partial void OnIdTipoEdificioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnInformacionChanging(string value);
    partial void OnInformacionChanged();
    #endregion
		
		public TB_TIPO_EDIFICIO()
		{
			this._TB_EDIFICIOs = new EntitySet<TB_EDIFICIO>(new Action<TB_EDIFICIO>(this.attach_TB_EDIFICIOs), new Action<TB_EDIFICIO>(this.detach_TB_EDIFICIOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEdificio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTipoEdificio
		{
			get
			{
				return this._IdTipoEdificio;
			}
			set
			{
				if ((this._IdTipoEdificio != value))
				{
					this.OnIdTipoEdificioChanging(value);
					this.SendPropertyChanging();
					this._IdTipoEdificio = value;
					this.SendPropertyChanged("IdTipoEdificio");
					this.OnIdTipoEdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(80)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Informacion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Informacion
		{
			get
			{
				return this._Informacion;
			}
			set
			{
				if ((this._Informacion != value))
				{
					this.OnInformacionChanging(value);
					this.SendPropertyChanging();
					this._Informacion = value;
					this.SendPropertyChanged("Informacion");
					this.OnInformacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_TIPO_EDIFICIO_TB_EDIFICIO", Storage="_TB_EDIFICIOs", ThisKey="IdTipoEdificio", OtherKey="IdTipoEdificio")]
		public EntitySet<TB_EDIFICIO> TB_EDIFICIOs
		{
			get
			{
				return this._TB_EDIFICIOs;
			}
			set
			{
				this._TB_EDIFICIOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_EDIFICIOs(TB_EDIFICIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_TIPO_EDIFICIO = this;
		}
		
		private void detach_TB_EDIFICIOs(TB_EDIFICIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_TIPO_EDIFICIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_TIPO_PERSONAJE")]
	public partial class TB_TIPO_PERSONAJE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTipoPersonaje;
		
		private string _Descripcion;
		
		private string _informacion;
		
		private EntitySet<TB_PERSONAJE> _TB_PERSONAJEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTipoPersonajeChanging(int value);
    partial void OnIdTipoPersonajeChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OninformacionChanging(string value);
    partial void OninformacionChanged();
    #endregion
		
		public TB_TIPO_PERSONAJE()
		{
			this._TB_PERSONAJEs = new EntitySet<TB_PERSONAJE>(new Action<TB_PERSONAJE>(this.attach_TB_PERSONAJEs), new Action<TB_PERSONAJE>(this.detach_TB_PERSONAJEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPersonaje", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTipoPersonaje
		{
			get
			{
				return this._IdTipoPersonaje;
			}
			set
			{
				if ((this._IdTipoPersonaje != value))
				{
					this.OnIdTipoPersonajeChanging(value);
					this.SendPropertyChanging();
					this._IdTipoPersonaje = value;
					this.SendPropertyChanged("IdTipoPersonaje");
					this.OnIdTipoPersonajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_informacion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string informacion
		{
			get
			{
				return this._informacion;
			}
			set
			{
				if ((this._informacion != value))
				{
					this.OninformacionChanging(value);
					this.SendPropertyChanging();
					this._informacion = value;
					this.SendPropertyChanged("informacion");
					this.OninformacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_TIPO_PERSONAJE_TB_PERSONAJE", Storage="_TB_PERSONAJEs", ThisKey="IdTipoPersonaje", OtherKey="IdTipoPersonaje")]
		public EntitySet<TB_PERSONAJE> TB_PERSONAJEs
		{
			get
			{
				return this._TB_PERSONAJEs;
			}
			set
			{
				this._TB_PERSONAJEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_PERSONAJEs(TB_PERSONAJE entity)
		{
			this.SendPropertyChanging();
			entity.TB_TIPO_PERSONAJE = this;
		}
		
		private void detach_TB_PERSONAJEs(TB_PERSONAJE entity)
		{
			this.SendPropertyChanging();
			entity.TB_TIPO_PERSONAJE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_TIPO_RECURSO")]
	public partial class TB_TIPO_RECURSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTipoRecurso;
		
		private string _Descripcion;
		
		private EntitySet<TB_RECURSO> _TB_RECURSOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTipoRecursoChanging(int value);
    partial void OnIdTipoRecursoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public TB_TIPO_RECURSO()
		{
			this._TB_RECURSOs = new EntitySet<TB_RECURSO>(new Action<TB_RECURSO>(this.attach_TB_RECURSOs), new Action<TB_RECURSO>(this.detach_TB_RECURSOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoRecurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTipoRecurso
		{
			get
			{
				return this._IdTipoRecurso;
			}
			set
			{
				if ((this._IdTipoRecurso != value))
				{
					this.OnIdTipoRecursoChanging(value);
					this.SendPropertyChanging();
					this._IdTipoRecurso = value;
					this.SendPropertyChanged("IdTipoRecurso");
					this.OnIdTipoRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_TIPO_RECURSO_TB_RECURSO", Storage="_TB_RECURSOs", ThisKey="IdTipoRecurso", OtherKey="IdTipoRecurso")]
		public EntitySet<TB_RECURSO> TB_RECURSOs
		{
			get
			{
				return this._TB_RECURSOs;
			}
			set
			{
				this._TB_RECURSOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_RECURSOs(TB_RECURSO entity)
		{
			this.SendPropertyChanging();
			entity.TB_TIPO_RECURSO = this;
		}
		
		private void detach_TB_RECURSOs(TB_RECURSO entity)
		{
			this.SendPropertyChanging();
			entity.TB_TIPO_RECURSO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_TIPO_TX")]
	public partial class TB_TIPO_TX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTipoTx;
		
		private string _Descripcion;
		
		private EntitySet<TB_TX> _TB_TXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTipoTxChanging(int value);
    partial void OnIdTipoTxChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public TB_TIPO_TX()
		{
			this._TB_TXes = new EntitySet<TB_TX>(new Action<TB_TX>(this.attach_TB_TXes), new Action<TB_TX>(this.detach_TB_TXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoTx", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTipoTx
		{
			get
			{
				return this._IdTipoTx;
			}
			set
			{
				if ((this._IdTipoTx != value))
				{
					this.OnIdTipoTxChanging(value);
					this.SendPropertyChanging();
					this._IdTipoTx = value;
					this.SendPropertyChanged("IdTipoTx");
					this.OnIdTipoTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_TIPO_TX_TB_TX", Storage="_TB_TXes", ThisKey="IdTipoTx", OtherKey="IdTipoTX")]
		public EntitySet<TB_TX> TB_TXes
		{
			get
			{
				return this._TB_TXes;
			}
			set
			{
				this._TB_TXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_TXes(TB_TX entity)
		{
			this.SendPropertyChanging();
			entity.TB_TIPO_TX = this;
		}
		
		private void detach_TB_TXes(TB_TX entity)
		{
			this.SendPropertyChanging();
			entity.TB_TIPO_TX = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_TX")]
	public partial class TB_TX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _IdTx;
		
		private System.Nullable<int> _IdLogEdificio;
		
		private System.Nullable<int> _IdTipoTX;
		
		private System.Nullable<int> _IdEstadoTx;
		
		private System.Nullable<System.DateTime> _FechaTx;
		
		private EntityRef<TB_ESTADO_TX> _TB_ESTADO_TX;
		
		private EntityRef<TB_LOG_EDIFICIO_USUARIO> _TB_LOG_EDIFICIO_USUARIO;
		
		private EntityRef<TB_TIPO_TX> _TB_TIPO_TX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTxChanging(decimal value);
    partial void OnIdTxChanged();
    partial void OnIdLogEdificioChanging(System.Nullable<int> value);
    partial void OnIdLogEdificioChanged();
    partial void OnIdTipoTXChanging(System.Nullable<int> value);
    partial void OnIdTipoTXChanged();
    partial void OnIdEstadoTxChanging(System.Nullable<int> value);
    partial void OnIdEstadoTxChanged();
    partial void OnFechaTxChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaTxChanged();
    #endregion
		
		public TB_TX()
		{
			this._TB_ESTADO_TX = default(EntityRef<TB_ESTADO_TX>);
			this._TB_LOG_EDIFICIO_USUARIO = default(EntityRef<TB_LOG_EDIFICIO_USUARIO>);
			this._TB_TIPO_TX = default(EntityRef<TB_TIPO_TX>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTx", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal IdTx
		{
			get
			{
				return this._IdTx;
			}
			set
			{
				if ((this._IdTx != value))
				{
					this.OnIdTxChanging(value);
					this.SendPropertyChanging();
					this._IdTx = value;
					this.SendPropertyChanged("IdTx");
					this.OnIdTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLogEdificio", DbType="Int")]
		public System.Nullable<int> IdLogEdificio
		{
			get
			{
				return this._IdLogEdificio;
			}
			set
			{
				if ((this._IdLogEdificio != value))
				{
					if (this._TB_LOG_EDIFICIO_USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLogEdificioChanging(value);
					this.SendPropertyChanging();
					this._IdLogEdificio = value;
					this.SendPropertyChanged("IdLogEdificio");
					this.OnIdLogEdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoTX", DbType="Int")]
		public System.Nullable<int> IdTipoTX
		{
			get
			{
				return this._IdTipoTX;
			}
			set
			{
				if ((this._IdTipoTX != value))
				{
					if (this._TB_TIPO_TX.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoTXChanging(value);
					this.SendPropertyChanging();
					this._IdTipoTX = value;
					this.SendPropertyChanged("IdTipoTX");
					this.OnIdTipoTXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstadoTx", DbType="Int")]
		public System.Nullable<int> IdEstadoTx
		{
			get
			{
				return this._IdEstadoTx;
			}
			set
			{
				if ((this._IdEstadoTx != value))
				{
					if (this._TB_ESTADO_TX.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstadoTxChanging(value);
					this.SendPropertyChanging();
					this._IdEstadoTx = value;
					this.SendPropertyChanged("IdEstadoTx");
					this.OnIdEstadoTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaTx", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaTx
		{
			get
			{
				return this._FechaTx;
			}
			set
			{
				if ((this._FechaTx != value))
				{
					this.OnFechaTxChanging(value);
					this.SendPropertyChanging();
					this._FechaTx = value;
					this.SendPropertyChanged("FechaTx");
					this.OnFechaTxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_ESTADO_TX_TB_TX", Storage="_TB_ESTADO_TX", ThisKey="IdEstadoTx", OtherKey="IdEstado", IsForeignKey=true)]
		public TB_ESTADO_TX TB_ESTADO_TX
		{
			get
			{
				return this._TB_ESTADO_TX.Entity;
			}
			set
			{
				TB_ESTADO_TX previousValue = this._TB_ESTADO_TX.Entity;
				if (((previousValue != value) 
							|| (this._TB_ESTADO_TX.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_ESTADO_TX.Entity = null;
						previousValue.TB_TXes.Remove(this);
					}
					this._TB_ESTADO_TX.Entity = value;
					if ((value != null))
					{
						value.TB_TXes.Add(this);
						this._IdEstadoTx = value.IdEstado;
					}
					else
					{
						this._IdEstadoTx = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_ESTADO_TX");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_LOG_EDIFICIO_USUARIO_TB_TX", Storage="_TB_LOG_EDIFICIO_USUARIO", ThisKey="IdLogEdificio", OtherKey="IdLogEdificioUsuario", IsForeignKey=true)]
		public TB_LOG_EDIFICIO_USUARIO TB_LOG_EDIFICIO_USUARIO
		{
			get
			{
				return this._TB_LOG_EDIFICIO_USUARIO.Entity;
			}
			set
			{
				TB_LOG_EDIFICIO_USUARIO previousValue = this._TB_LOG_EDIFICIO_USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._TB_LOG_EDIFICIO_USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_LOG_EDIFICIO_USUARIO.Entity = null;
						previousValue.TB_TXes.Remove(this);
					}
					this._TB_LOG_EDIFICIO_USUARIO.Entity = value;
					if ((value != null))
					{
						value.TB_TXes.Add(this);
						this._IdLogEdificio = value.IdLogEdificioUsuario;
					}
					else
					{
						this._IdLogEdificio = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_LOG_EDIFICIO_USUARIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_TIPO_TX_TB_TX", Storage="_TB_TIPO_TX", ThisKey="IdTipoTX", OtherKey="IdTipoTx", IsForeignKey=true)]
		public TB_TIPO_TX TB_TIPO_TX
		{
			get
			{
				return this._TB_TIPO_TX.Entity;
			}
			set
			{
				TB_TIPO_TX previousValue = this._TB_TIPO_TX.Entity;
				if (((previousValue != value) 
							|| (this._TB_TIPO_TX.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_TIPO_TX.Entity = null;
						previousValue.TB_TXes.Remove(this);
					}
					this._TB_TIPO_TX.Entity = value;
					if ((value != null))
					{
						value.TB_TXes.Add(this);
						this._IdTipoTX = value.IdTipoTx;
					}
					else
					{
						this._IdTipoTX = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_TIPO_TX");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_USUARIO")]
	public partial class TB_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private System.Nullable<int> _IdContacto;
		
		private string _NombreUsuario;
		
		private System.Data.Linq.Binary _Clave;
		
		private EntitySet<TB_LOG_EDIFICIO_USUARIO> _TB_LOG_EDIFICIO_USUARIOs;
		
		private EntityRef<TB_CONTACTO> _TB_CONTACTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnIdContactoChanging(System.Nullable<int> value);
    partial void OnIdContactoChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnClaveChanging(System.Data.Linq.Binary value);
    partial void OnClaveChanged();
    #endregion
		
		public TB_USUARIO()
		{
			this._TB_LOG_EDIFICIO_USUARIOs = new EntitySet<TB_LOG_EDIFICIO_USUARIO>(new Action<TB_LOG_EDIFICIO_USUARIO>(this.attach_TB_LOG_EDIFICIO_USUARIOs), new Action<TB_LOG_EDIFICIO_USUARIO>(this.detach_TB_LOG_EDIFICIO_USUARIOs));
			this._TB_CONTACTO = default(EntityRef<TB_CONTACTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContacto", DbType="Int")]
		public System.Nullable<int> IdContacto
		{
			get
			{
				return this._IdContacto;
			}
			set
			{
				if ((this._IdContacto != value))
				{
					if (this._TB_CONTACTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdContactoChanging(value);
					this.SendPropertyChanging();
					this._IdContacto = value;
					this.SendPropertyChanged("IdContacto");
					this.OnIdContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(50)")]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarBinary(46)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_USUARIO_TB_LOG_EDIFICIO_USUARIO", Storage="_TB_LOG_EDIFICIO_USUARIOs", ThisKey="IdUsuario", OtherKey="IdUsuarioSistema")]
		public EntitySet<TB_LOG_EDIFICIO_USUARIO> TB_LOG_EDIFICIO_USUARIOs
		{
			get
			{
				return this._TB_LOG_EDIFICIO_USUARIOs;
			}
			set
			{
				this._TB_LOG_EDIFICIO_USUARIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CONTACTO_TB_USUARIO", Storage="_TB_CONTACTO", ThisKey="IdContacto", OtherKey="IdContacto", IsForeignKey=true)]
		public TB_CONTACTO TB_CONTACTO
		{
			get
			{
				return this._TB_CONTACTO.Entity;
			}
			set
			{
				TB_CONTACTO previousValue = this._TB_CONTACTO.Entity;
				if (((previousValue != value) 
							|| (this._TB_CONTACTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CONTACTO.Entity = null;
						previousValue.TB_USUARIOs.Remove(this);
					}
					this._TB_CONTACTO.Entity = value;
					if ((value != null))
					{
						value.TB_USUARIOs.Add(this);
						this._IdContacto = value.IdContacto;
					}
					else
					{
						this._IdContacto = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_CONTACTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_LOG_EDIFICIO_USUARIOs(TB_LOG_EDIFICIO_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_USUARIO = this;
		}
		
		private void detach_TB_LOG_EDIFICIO_USUARIOs(TB_LOG_EDIFICIO_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TB_USUARIO = null;
		}
	}
}
#pragma warning restore 1591
